[tool.kedro]
package_name = "datathon_bcg_gamma"
project_name = "Datathon BCG Gamma"
project_version = "0.18.3"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/datathon_bcg_gamma -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
